#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Daiki Okamoto
# SPDX-License-Identifier: BSD-3-Clause

import sys

if len(sys.argv) <3:
    print("Error")
    sys.exit(1)
op = sys.argv[1]

try:
    nums = list(map(float, sys.argv[2:]))
except ValueError:
    print("valueerror")
    sys.argv[1]


result = nums[0]

for n in nums[1:]:
    if op == "-": 
        result -= n
    elif op in "*": 
        result *= n
    elif op == "/":
        result /= n
    else:
        print("Error")
        sys.exit(1)

print(result)
